dist: trusty
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - kalakris-cmake
    packages:
    - gcc-4.9   # Needed for C++11
    - g++-4.9   # Needed for C++11
    - gdb
    - ccache
    - cmake
    - valgrind
    - libboost-dev
    - libboost-filesystem-dev
    - libboost-system-dev

language: rust
rust:
  - nightly

before_install:
  - export ARROW_HOME=$TRAVIS_BUILD_DIR/arrow-install
  - export CC="gcc-4.9"
  - export CXX="g++-4.9"
  - $TRAVIS_BUILD_DIR/ci/prepare_arrow.sh

script:
  - cargo build --verbose
  - cargo test

notifications:
  email:
    - jihoonson@apache.org
